CREATE USER $DATABASES_USER  WITH PASSWORD '$DATABASES_PASSWORD ';
ALTER ROLE $DATABASES_USER  SET client_encoding TO 'utf8';
ALTER ROLE $DATABASES_USER  SET default_transaction_isolation TO 'read committed';
ALTER ROLE $DATABASES_USER  SET timezone TO 'UTC';

CREATE DATABASE $DATABASES_NAME OWNER $DATABASES_USER ;
