
from django.utils.translation import gettext_noop

SEX_CHOICES = (
    ('F', gettext_noop('Female')),
    ('M', gettext_noop('Male')),
    ('U', gettext_noop('Unsure')),
    )

NATIONALITIES_CHOICES= (
    # To do : add country that no longer exist (prussia, etc... )
    ('Afghan', gettext_noop('Afghan')),
    ('Albanian', gettext_noop('Albanian')),
    ('Algerian', gettext_noop('Algerian')),
    ('American', gettext_noop('American')), 
    ('Andorran', gettext_noop('Andorran')), 
    ('Angolan', gettext_noop('Angolan')), 
    ('Antiguans', gettext_noop('Antiguans')),
    ('Argentinean', gettext_noop('Argentinean')),
    ('Armenian', gettext_noop('Armenian')),
    ('Australian', gettext_noop('Australian')),
    ('Austrian', gettext_noop('Austrian')),
    ('Azerbaijani', gettext_noop('Azerbaijani')),
    ('Bahamian', gettext_noop('Bahamian')),
    ('Bahraini', gettext_noop('Bahraini')),
    ('Bangladeshi', gettext_noop('Bangladeshi')),
    ('Barbadian', gettext_noop('Barbadian')),
    ('Barbudans', gettext_noop('Barbudans')),
    ('Batswana', gettext_noop('Batswana')),
    ('Belarusian', gettext_noop('Belarusian')),
    ('Belgian', gettext_noop('Belgian')),
    ('Belizean', gettext_noop('Belizean')),
    ('Beninese', gettext_noop('Beninese')), 
    ('Bhutanese', gettext_noop('Bhutanese')),
    ('Bolivian', gettext_noop('Bolivian')),
    ('Bosnian', gettext_noop('Bosnian')),
    ('Brazilian', gettext_noop('Brazilian')),
    ('British', gettext_noop('British')),
    ('Bruneian', gettext_noop('Bruneian')),
    ('Bulgarian', gettext_noop('Bulgarian')),
    ('Burkinabe', gettext_noop('Burkinabe')),
    ('Burmese', gettext_noop('Burmese')),
    ('Burundian', gettext_noop('Burundian')),
    ('Cambodian', gettext_noop('Cambodian')),
    ('Cameroonian', gettext_noop('Cameroonian')),
    ('Canadian', gettext_noop('Canadian')),
    ('Cape Verdean', gettext_noop('Cape Verdean')),
    ('Central African', gettext_noop('Central African')),
    ('Chadian', gettext_noop('Chadian')),
    ('Chilean', gettext_noop('Chilean')),
    ('Chinese', gettext_noop('Chinese')),
    ('Colombian', gettext_noop('Colombian')),
    ('Comoran', gettext_noop('Comoran')),
    ('Congolese', gettext_noop('Congolese')),
    ('Costa Rican', gettext_noop('Costa Rican')),
    ('Croatian', gettext_noop('Croatian')),
    ('Cuban', gettext_noop('Cuban')),
    ('Cypriot', gettext_noop('Cypriot')),
    ('Czech', gettext_noop('Czech')),
    ('Danish', gettext_noop('Danish')),
    ('Djibouti', gettext_noop('Djibouti')),
    ('Dominican', gettext_noop('Dominican')),
    ('Dutch', gettext_noop('Dutch')),
    ('Dutchman', gettext_noop('Dutchman')),
    ('Dutchwoman', gettext_noop('Dutchwoman')),
    ('East Timorese', gettext_noop('East Timorese')),
    ('Ecuadorean', gettext_noop('Ecuadorean')),
    ('Egyptian', gettext_noop('Egyptian')),
    ('Emirian', gettext_noop('Emirian')),
    ('Equatorial Guinean', gettext_noop('Equatorial Guinean')),
    ('Eritrean', gettext_noop('Eritrean')),
    ('Estonian', gettext_noop('Estonian')),
    ('Ethiopian', gettext_noop('Ethiopian')),
    ('Fijian', gettext_noop('Fijian')),
    ('Filipino', gettext_noop('Filipino')),
    ('Finnish', gettext_noop('Finnish')),
    ('French', gettext_noop('French')),
    ('Gabonese', gettext_noop('Gabonese')),
    ('Gambian', gettext_noop('Gambian')),
    ('Georgian', gettext_noop('Georgian')),
    ('German', gettext_noop('German')),
    ('Ghanaian', gettext_noop('Ghanaian')),
    ('Greek', gettext_noop('Greek')),
    ('Grenadian', gettext_noop('Grenadian')),
    ('Guatemalan', gettext_noop('Guatemalan')),
    ('Guinea-Bissauan', gettext_noop('Guinea-Bissauan')),
    ('Guinean', gettext_noop('Guinean')),
    ('Guyanese', gettext_noop('Guyanese')),
    ('Haitian', gettext_noop('Haitian')),
    ('Herzegovinian', gettext_noop('Herzegovinian')),
    ('Honduran', gettext_noop('Honduran')),
    ('Hungarian', gettext_noop('Hungarian')),
    ('I-Kiribati', gettext_noop('I-Kiribati')),
    ('Icelander', gettext_noop('Icelander')),
    ('Indian', gettext_noop('Indian')),
    ('Indonesian', gettext_noop('Indonesian')),
    ('Iranian', gettext_noop('Iranian')),
    ('Iraqi', gettext_noop('Iraqi')),
    ('Irish', gettext_noop('Irish')),
    ('Israeli', gettext_noop('Israeli')),
    ('Italian', gettext_noop('Italian')),
    ('Ivorian', gettext_noop('Ivorian')),
    ('Jamaican', gettext_noop('Jamaican')),
    ('Japanese', gettext_noop('Japanese')),
    ('Jordanian', gettext_noop('Jordanian')),
    ('Kazakhstani', gettext_noop('Kazakhstani')),
    ('Kenyan', gettext_noop('Kenyan')),
    ('Kittian and Nevisian', gettext_noop('Kittian and Nevisian')),
    ('Kuwaiti', gettext_noop('Kuwaiti')),
    ('Kyrgyz', gettext_noop('Kyrgyz')),
    ('Laotian', gettext_noop('Laotian')),
    ('Latvian', gettext_noop('Latvian')),
    ('Lebanese', gettext_noop('Lebanese')),
    ('Liberian', gettext_noop('Liberian')),
    ('Libyan', gettext_noop('Libyan')),
    ('Liechtensteiner', gettext_noop('Liechtensteiner')),
    ('Lithuanian', gettext_noop('Lithuanian')),
    ('Luxembourger', gettext_noop('Luxembourger')),
    ('Macedonian', gettext_noop('Macedonian')),
    ('Malagasy', gettext_noop('Malagasy')),
    ('Malawian', gettext_noop('Malawian')),
    ('Malaysian', gettext_noop('Malaysian')),
    ('Maldivan', gettext_noop('Maldivan')),
    ('Malian', gettext_noop('Malian')),
    ('Maltese', gettext_noop('Maltese')),
    ('Marshallese', gettext_noop('Marshallese')),
    ('Mauritanian', gettext_noop('Mauritanian')),
    ('Mauritian', gettext_noop('Mauritian')),
    ('Mexican', gettext_noop('Mexican')),
    ('Micronesian', gettext_noop('Micronesian')),
    ('Moldovan', gettext_noop('Moldovan')),
    ('Monacan', gettext_noop('Monacan')),
    ('Mongolian', gettext_noop('Mongolian')),
    ('Moroccan', gettext_noop('Moroccan')),
    ('Mosotho', gettext_noop('Mosotho')),
    ('Motswana', gettext_noop('Motswana')),
    ('Mozambican', gettext_noop('Mozambican')),
    ('Namibian', gettext_noop('Namibian')),
    ('Nauruan', gettext_noop('Nauruan')),
    ('Nepalese', gettext_noop('Nepalese')),
    ('Netherlander', gettext_noop('Netherlander')),
    ('New Zealander', gettext_noop('New Zealander')),
    ('Ni-Vanuatu', gettext_noop('Ni-Vanuatu')),
    ('Nicaraguan', gettext_noop('Nicaraguan')),
    ('Nigerian', gettext_noop('Nigerian')),
    ('Nigerien', gettext_noop('Nigerien')),
    ('North Korean', gettext_noop('North Korean')),
    ('Northern Irish', gettext_noop('Northern Irish')),
    ('Norwegian', gettext_noop('Norwegian')),
    ('Omani', gettext_noop('Omani')),
    ('Pakistani', gettext_noop('Pakistani')),
    ('Palauan', gettext_noop('Palauan')),
    ('Panamanian', gettext_noop('Panamanian')),
    ('Papua New Guinean', gettext_noop('Papua New Guinean')),
    ('Paraguayan', gettext_noop('Paraguayan')),
    ('Peruvian', gettext_noop('Peruvian')),
    ('Polish', gettext_noop('Polish')),
    ('Portuguese', gettext_noop('Portuguese')),
    ('Qatari', gettext_noop('Qatari')),
    ('Romanian', gettext_noop('Romanian')),
    ('Russian', gettext_noop('Russian')),
    ('Rwandan', gettext_noop('Rwandan')),
    ('Saint Lucian', gettext_noop('Saint Lucian')),
    ('Salvadoran', gettext_noop('Salvadoran')),
    ('Samoan', gettext_noop('Samoan')),
    ('San Marinese', gettext_noop('San Marinese')),
    ('Sao Tomean', gettext_noop('Sao Tomean')),
    ('Saudi', gettext_noop('Saudi')),
    ('Scottish', gettext_noop('Scottish')),
    ('Senegalese', gettext_noop('Senegalese')),
    ('Serbian', gettext_noop('Serbian')),
    ('Seychellois', gettext_noop('Seychellois')),
    ('Sierra Leonean', gettext_noop('Sierra Leonean')),
    ('Singaporean', gettext_noop('Singaporean')),
    ('Slovakian', gettext_noop('Slovakian')),
    ('Slovenian', gettext_noop('Slovenian')),
    ('Solomon Islander', gettext_noop('Solomon Islander')),
    ('Somali', gettext_noop('Somali')),
    ('South African', gettext_noop('South African')),
    ('South Korean', gettext_noop('South Korean')),
    ('Spanish', gettext_noop('Spanish')),
    ('Sri Lankan', gettext_noop('Sri Lankan')),
    ('Sudanese', gettext_noop('Sudanese')),
    ('Surinamer', gettext_noop('Surinamer')),
    ('Swazi', gettext_noop('Swazi')),
    ('Swedish', gettext_noop('Swedish')),
    ('Swiss', gettext_noop('Swiss')),
    ('Syrian', gettext_noop('Syrian')),
    ('Taiwanese', gettext_noop('Taiwanese')),
    ('Tajik', gettext_noop('Tajik')),
    ('Tanzanian', gettext_noop('Tanzanian')),
    ('Thai', gettext_noop('Thai')),
    ('Togolese', gettext_noop('Togolese')),
    ('Tongan', gettext_noop('Tongan')),
    ('Trinidadian or Tobagonian', gettext_noop('Trinidadian or Tobagonian')),
    ('Tunisian', gettext_noop('Tunisian')),
    ('Turkish', gettext_noop('Turkish')),
    ('Tuvaluan', gettext_noop('Tuvaluan')),
    ('Ugandan', gettext_noop('Ugandan')),
    ('Ukrainian', gettext_noop('Ukrainian')),
    ('Uruguayan', gettext_noop('Uruguayan')),
    ('Uzbekistani', gettext_noop('Uzbekistani')),
    ('Venezuelan', gettext_noop('Venezuelan')),
    ('Vietnamese', gettext_noop('Vietnamese')),
    ('Welsh', gettext_noop('Welsh')),
    ('Yemenite', gettext_noop('Yemenite')),
    ('Zambian', gettext_noop('Zambian')),
    ('Zimbabwean', gettext_noop('Zimbabwean'))
    )