
# from django.utils.translation import _

from django.utils.translation import gettext_lazy as _


SEX_CHOICES = (
    ('F', _('Female')),
    ('M', _('Male')),
    ('U', _('Unsure')),
    )

NATIONALITIES_CHOICES= (
    # To do : add country that no longer exist (prussia, persia etc... )
    ('Afghan', _('Afghan')),
    ('Albanian', _('Albanian')),
    ('Algerian', _('Algerian')),
    ('American', _('American')), 
    ('Andorran', _('Andorran')), 
    ('Angolan', _('Angolan')), 
    ('Antiguans', _('Antiguans')),
    ('Argentinean', _('Argentinean')),
    ('Armenian', _('Armenian')),
    ('Australian', _('Australian')),
    ('Austrian', _('Austrian')),
    ('Azerbaijani', _('Azerbaijani')),
    ('Bahamian', _('Bahamian')),
    ('Bahraini', _('Bahraini')),
    ('Bangladeshi', _('Bangladeshi')),
    ('Barbadian', _('Barbadian')),
    ('Barbudans', _('Barbudans')),
    ('Batswana', _('Batswana')),
    ('Belarusian', _('Belarusian')),
    ('Belgian', _('Belgian')),
    ('Belizean', _('Belizean')),
    ('Beninese', _('Beninese')), 
    ('Bhutanese', _('Bhutanese')),
    ('Bolivian', _('Bolivian')),
    ('Bosnian', _('Bosnian')),
    ('Brazilian', _('Brazilian')),
    ('British', _('British')),
    ('Bruneian', _('Bruneian')),
    ('Bulgarian', _('Bulgarian')),
    ('Burkinabe', _('Burkinabe')),
    ('Burmese', _('Burmese')),
    ('Burundian', _('Burundian')),
    ('Cambodian', _('Cambodian')),
    ('Cameroonian', _('Cameroonian')),
    ('Canadian', _('Canadian')),
    ('Cape Verdean', _('Cape Verdean')),
    ('Central African', _('Central African')),
    ('Chadian', _('Chadian')),
    ('Chilean', _('Chilean')),
    ('Chinese', _('Chinese')),
    ('Colombian', _('Colombian')),
    ('Comoran', _('Comoran')),
    ('Congolese', _('Congolese')),
    ('Costa Rican', _('Costa Rican')),
    ('Croatian', _('Croatian')),
    ('Cuban', _('Cuban')),
    ('Cypriot', _('Cypriot')),
    ('Czech', _('Czech')),
    ('Danish', _('Danish')),
    ('Djibouti', _('Djibouti')),
    ('Dominican', _('Dominican')),
    ('Dutch', _('Dutch')),
    ('Dutchman', _('Dutchman')),
    ('Dutchwoman', _('Dutchwoman')),
    ('East Timorese', _('East Timorese')),
    ('Ecuadorean', _('Ecuadorean')),
    ('Egyptian', _('Egyptian')),
    ('Emirian', _('Emirian')),
    ('Equatorial Guinean', _('Equatorial Guinean')),
    ('Eritrean', _('Eritrean')),
    ('Estonian', _('Estonian')),
    ('Ethiopian', _('Ethiopian')),
    ('Fijian', _('Fijian')),
    ('Filipino', _('Filipino')),
    ('Finnish', _('Finnish')),
    ('French', _('French')),
    ('Gabonese', _('Gabonese')),
    ('Gambian', _('Gambian')),
    ('Georgian', _('Georgian')),
    ('German', _('German')),
    ('Ghanaian', _('Ghanaian')),
    ('Greek', _('Greek')),
    ('Grenadian', _('Grenadian')),
    ('Guatemalan', _('Guatemalan')),
    ('Guinea-Bissauan', _('Guinea-Bissauan')),
    ('Guinean', _('Guinean')),
    ('Guyanese', _('Guyanese')),
    ('Haitian', _('Haitian')),
    ('Herzegovinian', _('Herzegovinian')),
    ('Honduran', _('Honduran')),
    ('Hungarian', _('Hungarian')),
    ('I-Kiribati', _('I-Kiribati')),
    ('Icelander', _('Icelander')),
    ('Indian', _('Indian')),
    ('Indonesian', _('Indonesian')),
    ('Iranian', _('Iranian')),
    ('Iraqi', _('Iraqi')),
    ('Irish', _('Irish')),
    ('Israeli', _('Israeli')),
    ('Italian', _('Italian')),
    ('Ivorian', _('Ivorian')),
    ('Jamaican', _('Jamaican')),
    ('Japanese', _('Japanese')),
    ('Jordanian', _('Jordanian')),
    ('Kazakhstani', _('Kazakhstani')),
    ('Kenyan', _('Kenyan')),
    ('Kittian and Nevisian', _('Kittian and Nevisian')),
    ('Kuwaiti', _('Kuwaiti')),
    ('Kyrgyz', _('Kyrgyz')),
    ('Laotian', _('Laotian')),
    ('Latvian', _('Latvian')),
    ('Lebanese', _('Lebanese')),
    ('Liberian', _('Liberian')),
    ('Libyan', _('Libyan')),
    ('Liechtensteiner', _('Liechtensteiner')),
    ('Lithuanian', _('Lithuanian')),
    ('Luxembourger', _('Luxembourger')),
    ('Macedonian', _('Macedonian')),
    ('Malagasy', _('Malagasy')),
    ('Malawian', _('Malawian')),
    ('Malaysian', _('Malaysian')),
    ('Maldivan', _('Maldivan')),
    ('Malian', _('Malian')),
    ('Maltese', _('Maltese')),
    ('Marshallese', _('Marshallese')),
    ('Mauritanian', _('Mauritanian')),
    ('Mauritian', _('Mauritian')),
    ('Mexican', _('Mexican')),
    ('Micronesian', _('Micronesian')),
    ('Moldovan', _('Moldovan')),
    ('Monacan', _('Monacan')),
    ('Mongolian', _('Mongolian')),
    ('Moroccan', _('Moroccan')),
    ('Mosotho', _('Mosotho')),
    ('Motswana', _('Motswana')),
    ('Mozambican', _('Mozambican')),
    ('Namibian', _('Namibian')),
    ('Nauruan', _('Nauruan')),
    ('Nepalese', _('Nepalese')),
    ('Netherlander', _('Netherlander')),
    ('New Zealander', _('New Zealander')),
    ('Ni-Vanuatu', _('Ni-Vanuatu')),
    ('Nicaraguan', _('Nicaraguan')),
    ('Nigerian', _('Nigerian')),
    ('Nigerien', _('Nigerien')),
    ('North Korean', _('North Korean')),
    ('Northern Irish', _('Northern Irish')),
    ('Norwegian', _('Norwegian')),
    ('Omani', _('Omani')),
    ('Other', _('Other')),    
    ('Pakistani', _('Pakistani')),
    ('Palauan', _('Palauan')),
    ('Panamanian', _('Panamanian')),
    ('Papua New Guinean', _('Papua New Guinean')),
    ('Paraguayan', _('Paraguayan')),
    ('Peruvian', _('Peruvian')),
    ('Polish', _('Polish')),
    ('Portuguese', _('Portuguese')),
    ('Qatari', _('Qatari')),
    ('Romanian', _('Romanian')),
    ('Russian', _('Russian')),
    ('Rwandan', _('Rwandan')),
    ('Saint Lucian', _('Saint Lucian')),
    ('Salvadoran', _('Salvadoran')),
    ('Samoan', _('Samoan')),
    ('San Marinese', _('San Marinese')),
    ('Sao Tomean', _('Sao Tomean')),
    ('Saudi', _('Saudi')),
    ('Scottish', _('Scottish')),
    ('Senegalese', _('Senegalese')),
    ('Serbian', _('Serbian')),
    ('Seychellois', _('Seychellois')),
    ('Sierra Leonean', _('Sierra Leonean')),
    ('Singaporean', _('Singaporean')),
    ('Slovakian', _('Slovakian')),
    ('Slovenian', _('Slovenian')),
    ('Solomon Islander', _('Solomon Islander')),
    ('Somali', _('Somali')),
    ('South African', _('South African')),
    ('South Korean', _('South Korean')),
    ('Spanish', _('Spanish')),
    ('Sri Lankan', _('Sri Lankan')),
    ('Sudanese', _('Sudanese')),
    ('Surinamer', _('Surinamer')),
    ('Swazi', _('Swazi')),
    ('Swedish', _('Swedish')),
    ('Swiss', _('Swiss')),
    ('Syrian', _('Syrian')),
    ('Taiwanese', _('Taiwanese')),
    ('Tajik', _('Tajik')),
    ('Tanzanian', _('Tanzanian')),
    ('Thai', _('Thai')),
    ('Togolese', _('Togolese')),
    ('Tongan', _('Tongan')),
    ('Trinidadian or Tobagonian', _('Trinidadian or Tobagonian')),
    ('Tunisian', _('Tunisian')),
    ('Turkish', _('Turkish')),
    ('Tuvaluan', _('Tuvaluan')),
    ('Ugandan', _('Ugandan')),
    ('Ukrainian', _('Ukrainian')),
    ('Uruguayan', _('Uruguayan')),
    ('Uzbekistani', _('Uzbekistani')),
    ('Venezuelan', _('Venezuelan')),
    ('Vietnamese', _('Vietnamese')),
    ('Welsh', _('Welsh')),
    ('Yemenite', _('Yemenite')),
    ('Zambian', _('Zambian')),
    ('Zimbabwean', _('Zimbabwean'))
    )


